[package]
name = "rustbasic-translatable"
version = "0.0.5"
edition = "2024"
build = "build.rs"
description = "Multi-language JSON translation and localization package for the RustBasic Framework."
license = "MIT"
readme = "README.md"
homepage = "https://github.com/herisvan321/rustbasic"
repository = "https://github.com/herisvan321/rustbasic-translatable"
documentation = "https://docs.rs/rustbasic-translatable"
keywords = ["web", "framework", "translation", "localization", "i18n"]
categories = ["web-programming", "localization"]

[lib]
name = "rustbasic_translatable"
path = "src/lib.rs"

[dependencies]
rustbasic-core = "0.0"
